02-11 23:43:15 jdbc[2]: SQLException
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-127]
	at org.h2.message.Message.getSQLException(Message.java:110)
	at org.h2.message.Message.getSQLException(Message.java:121)
	at org.h2.message.Message.getSQLException(Message.java:74)
	at org.h2.message.Message.getSQLException(Message.java:156)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1342)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1320)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:231)
	at org.h2.jaqu.Db.prepare(Db.java:355)
	at org.h2.jaqu.Db.getRelationByRelationTable(Db.java:431)
	at org.h2.jaqu.Db.getRelationFromDb(Db.java:478)
	at org.h2.jaqu.Db.getRelationFromDb(Db.java:336)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.centimia.jaqu.test.entity.Person.getAddresses(Person.java:65)
	at com.centimia.jaqu.test.entity.EntitySessionTests.run(EntitySessionTests.java:94)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at com.centimia.jaqu.test.JaquTestSuite.main(JaquTestSuite.java:55)
